version: '3.8'

services:
  # Development environment
  dev:
    build:
      context: .
      target: build-stage
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: npm run dev
    environment:
      - NODE_ENV=development

  # Production environment
  prod:
    build:
      context: .
      target: production-stage
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
